### ISSUE TITLE
Order of information in files

### ISSUE THREAD

**Issue by EmilieSkog** [3lbits/Grunnprofil#217]
Classes are listed in alphabetical order with a double lineshift between each object. 
For each object the attributes are listed first, then associations. Under this inheritance is included in the order of inheritence hierarchy and inherited attributes are included in alphabetical order.

Exception: mRID is always the first attribute of an object.

**Comment by Sveino** [comment]
I think this is good, but we would need to have code that can parse an existing file and create this in the case we are exporting the file from a tool that does not support this. We should include this in the documentation and add an example.
