### ISSUE TITLE
Meterpoint in to EQ-profile

### ISSUE THREAD

**Issue by vaag1988** [3lbits/Grunnprofil#301]
The EQ-profile is central and has all the necessary details to understand connectivity, topology and run load flow analyses. 

However, the aggregation of meter points into generic load classes is a bit old fashion. Today everything is more data driven and we would like to include UsagePoints with EAN-number into the EQ-profile so that we have enough information in the EQ-profile alone to run load flow analysis based on AMI-data.

We think it will be a lot easier to link the data based on EAN rather than the CIM-id for most companies and we would like to keep the UsagePoints disaggregated to serve potential flexibility trading features.

**Comment by Sveino** [comment]
Agree. We have tried to address this in our test data. See [Measurement And MeterReading Specification](https://github.com/digin-energi/Grunnprofil/blob/develop/DIGIN10/docs/MeasurementAndMeterReadingSpecification.adoc).
